#!/bin/bash
# Скрипт для рекомендаций по очистке кэша браузера

echo "=== Рекомендации по очистке кэша браузера ==="
echo ""
echo "Для полного решения проблем с отображением интерфейса может потребоваться"
echo "очистить кэш браузера. Выполните следующие действия:"
echo ""
echo "Chrome:"
echo "  1. Нажмите Ctrl+Shift+Delete (Windows/Linux) или Command+Shift+Delete (Mac)"
echo "  2. Выберите 'Кэшированные изображения и файлы'"
echo "  3. Нажмите 'Очистить данные'"
echo ""
echo "Firefox:"
echo "  1. Нажмите Ctrl+Shift+Delete (Windows/Linux) или Command+Shift+Delete (Mac)"
echo "  2. Выберите только 'Кэш'"
echo "  3. Нажмите 'Удалить'"
echo ""
echo "Safari:"
echo "  1. Откройте меню Safari > Preferences > Advanced"
echo "  2. Отметьте 'Show Develop menu in menu bar'"
echo "  3. Нажмите Develop > Empty Caches"
echo ""
echo "После очистки кэша перезагрузите страницу (Ctrl+F5 или Command+R)"
echo ""
echo "=== Готово ==="
