# Generated by Django 5.2.1 on 2025-05-23 08:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0013_alter_lmsusertestresult_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, verbose_name='risk level')),
                ('reason', models.TextField(verbose_name='reason')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='onboarding.useronboardingassignment', verbose_name='assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI insight',
                'verbose_name_plural': 'AI insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
