# Generated by Django 5.2.1 on 2025-05-23 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0001_initial'),
        ('onboarding', '0014_onboardingstep_is_virtual_meeting_virtualmeetingslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_text', models.TextField(verbose_name='hint text')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='generated at')),
                ('dismissed', models.BooleanField(default=False, verbose_name='dismissed')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ai_insights', to='onboarding.useronboardingassignment', verbose_name='assignment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ai_insights', to='onboarding.onboardingstep', verbose_name='step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ai_insights', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'client AI insight',
                'verbose_name_plural': 'client AI insights',
                'ordering': ['-generated_at'],
                'unique_together': {('user', 'step', 'assignment')},
            },
        ),
    ]
