# Generated by Django 5.2.1 on 2025-05-27 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0002_clientaiinsight'),
        ('onboarding', '0015_alter_aichatmessage_step_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField(verbose_name='recommendation text')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='generated at')),
                ('dismissed', models.BooleanField(default=False, verbose_name='dismissed')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='onboarding.useronboardingassignment', verbose_name='assignment')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='onboarding.onboardingstep', verbose_name='step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI recommendation',
                'verbose_name_plural': 'AI recommendations',
                'ordering': ['-generated_at'],
            },
        ),
    ]
