# Generated by Django 5.2.1 on 2025-05-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0004_migrate_data_to_v2'),
        ('ai_insights', '0016_alter_departmentlearningmetric_id_and_more'),
        ('ai_insights', '0016_unified_insights_model'),
    ]

    operations = [
    ]
