# Generated by Django 5.2.1 on 2025-05-31 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0017_merge_20250531_2006'),
        ('departments', '0002_add_manager_field'),
        ('onboarding', '0019_alter_attachment_id_alter_enhancedlmsquestion_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendationV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('recommendation_text', models.TextField(verbose_name='recommendation text')),
                ('recommendation_type', models.CharField(choices=[('training', 'Training'), ('feedback', 'Feedback'), ('progress', 'Progress'), ('general', 'General')], default='general', max_length=30, verbose_name='recommendation type')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20, verbose_name='priority')),
                ('status', models.CharField(choices=[('active', 'Active'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='active', max_length=20, verbose_name='status')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='reason')),
                ('impact_description', models.TextField(blank=True, null=True, verbose_name='impact description')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='generated at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('accepted_reason', models.TextField(blank=True, null=True, verbose_name='accepted reason')),
                ('rejected_reason', models.TextField(blank=True, null=True, verbose_name='rejected reason')),
            ],
            options={
                'verbose_name': 'AI recommendation v2',
                'verbose_name_plural': 'AI recommendations v2',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='aiinsightv2',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI insight', 'verbose_name_plural': 'AI insights'},
        ),
        migrations.AlterModelOptions(
            name='insighttag',
            options={'ordering': ['name'], 'verbose_name': 'insight tag', 'verbose_name_plural': 'insight tags'},
        ),
        migrations.RemoveIndex(
            model_name='aiinsightv2',
            name='ai_insights_insight__072c16_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiinsightv2',
            name='ai_insights_risk_le_b7d1a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiinsightv2',
            name='ai_insights_status_1a9876_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiinsightv2',
            name='ai_insights_created_234567_idx',
        ),
        migrations.RemoveField(
            model_name='aiinsightv2',
            name='question',
        ),
        migrations.RemoveField(
            model_name='aiinsightv2',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='aiinsightv2',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='aiinsightv2',
            name='test',
        ),
        migrations.AddField(
            model_name='aiinsightv2',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights_v2', to='onboarding.useronboardingassignment', verbose_name='assignment'),
        ),
        migrations.AddField(
            model_name='aiinsightv2',
            name='level',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], default='medium', max_length=20, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='aiinsightv2',
            name='source',
            field=models.CharField(default='system', max_length=100, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='aiinsightv2',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='source ID'),
        ),
        migrations.AlterField(
            model_name='aiinsightv2',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights_v2', to='departments.department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='aiinsightv2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiinsightv2',
            name='insight_type',
            field=models.CharField(choices=[('training', 'Training'), ('feedback', 'Feedback'), ('schedule', 'Schedule'), ('analytics', 'Analytics'), ('recommendation', 'Recommendation')], max_length=30, verbose_name='insight type'),
        ),
        migrations.AlterField(
            model_name='aiinsightv2',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='new', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='aiinsightv2',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights_v2', to='onboarding.onboardingstep', verbose_name='step'),
        ),
        migrations.AlterField(
            model_name='aiinsightv2',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights_v2', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='insighttag',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='insighttag',
            name='color',
            field=models.CharField(default='blue', max_length=20, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='insighttag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='insighttag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='insighttag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_tags', to='ai_insights.insighttag', verbose_name='parent tag'),
        ),
        migrations.AlterField(
            model_name='insighttag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='airecommendationv2',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations_v2', to='onboarding.useronboardingassignment', verbose_name='assignment'),
        ),
        migrations.AddField(
            model_name='airecommendationv2',
            name='insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='ai_insights.aiinsight', verbose_name='insight'),
        ),
        migrations.AddField(
            model_name='airecommendationv2',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='processed by'),
        ),
        migrations.AddField(
            model_name='airecommendationv2',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations_v2', to='onboarding.onboardingstep', verbose_name='step'),
        ),
        migrations.AddField(
            model_name='airecommendationv2',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recommendations', to='ai_insights.insighttag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='airecommendationv2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations_v2', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
