# Generated by Django 5.2 on 2025-05-21 13:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_programs', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'onboarding program',
                'verbose_name_plural': 'onboarding programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('step_type', models.CharField(choices=[('task', 'Task'), ('meeting', 'Meeting'), ('training', 'Training')], default='task', max_length=20, verbose_name='step type')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('is_required', models.BooleanField(default=True, verbose_name='is required')),
                ('deadline_days', models.PositiveIntegerField(blank=True, help_text='Number of days to complete after assignment', null=True, verbose_name='deadline days')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='onboarding.onboardingprogram', verbose_name='program')),
            ],
            options={
                'verbose_name': 'onboarding step',
                'verbose_name_plural': 'onboarding steps',
                'ordering': ['program', 'order'],
                'unique_together': {('program', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserOnboardingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='assigned at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='status')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='onboarding.onboardingprogram', verbose_name='program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_assignments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user onboarding assignment',
                'verbose_name_plural': 'user onboarding assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'program')},
            },
        ),
        migrations.CreateModel(
            name='UserStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('done', 'Done')], default='not_started', max_length=20, verbose_name='status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='onboarding.onboardingstep', verbose_name='step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user step progress',
                'verbose_name_plural': 'user step progress',
                'ordering': ['step__order'],
                'unique_together': {('user', 'step')},
            },
        ),
    ]
