# Generated by Django 5.2.1 on 2025-05-21 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('great', 'Great'), ('good', 'Good'), ('neutral', 'Neutral'), ('bad', 'Bad'), ('terrible', 'Terrible')], max_length=20, verbose_name='value')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='onboarding.useronboardingassignment', verbose_name='assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_moods', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'feedback mood',
                'verbose_name_plural': 'feedback moods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_feedbacks', to='onboarding.useronboardingassignment', verbose_name='assignment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='onboarding.onboardingstep', verbose_name='step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'step feedback',
                'verbose_name_plural': 'step feedbacks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'step', 'assignment')},
            },
        ),
    ]
