# Generated by Django 5.2.1 on 2025-05-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_feedbackmood_stepfeedback'),
    ]

    # Эта миграция была создана для добавления моделей обратной связи,
    # но модели уже были добавлены в предыдущей миграции.
    operations = [
    ]
