# Generated by Django 5.2.1 on 2025-05-21 13:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_add_feedback_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='question text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'LMS question',
                'verbose_name_plural': 'LMS questions',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LMSOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='option text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='onboarding.lmsquestion', verbose_name='question')),
            ],
            options={
                'verbose_name': 'LMS option',
                'verbose_name_plural': 'LMS options',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LMSTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_tests', to='onboarding.onboardingstep', verbose_name='onboarding step')),
            ],
            options={
                'verbose_name': 'LMS test',
                'verbose_name_plural': 'LMS tests',
                'unique_together': {('step',)},
            },
        ),
        migrations.AddField(
            model_name='lmsquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='onboarding.lmstest', verbose_name='test'),
        ),
        migrations.CreateModel(
            name='LMSModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('file', 'File')], max_length=20, verbose_name='content type')),
                ('content', models.TextField(help_text='URL видео, текстовое содержимое или путь к файлу', verbose_name='content')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_modules', to='onboarding.onboardingstep', verbose_name='onboarding step')),
            ],
            options={
                'verbose_name': 'LMS module',
                'verbose_name_plural': 'LMS modules',
                'ordering': ['step', 'order'],
                'unique_together': {('step', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LMSUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='answered at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='onboarding.lmsquestion', verbose_name='question')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='onboarding.lmsoption', verbose_name='selected option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_answers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'LMS user answer',
                'verbose_name_plural': 'LMS user answers',
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='LMSUserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField(default=False, verbose_name='is passed')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='max score')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='completed at')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='onboarding.lmstest', verbose_name='test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_test_results', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'LMS user test result',
                'verbose_name_plural': 'LMS user test results',
                'unique_together': {('user', 'test')},
            },
        ),
    ]
