# Generated by Django 5.2 on 2025-05-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_lmsquestion_lmsoption_lmstest_lmsquestion_test_and_more'),
    ]

    operations = [
    ]
