# Generated by Django 5.2 on 2025-05-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_merge_20250522_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepfeedback',
            name='auto_tag',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('unclear_instruction', 'Unclear Instruction'), ('delay_warning', 'Delay Warning')], max_length=30, null=True, verbose_name='auto tag'),
        ),
        migrations.AddField(
            model_name='stepfeedback',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True, verbose_name='sentiment score'),
        ),
    ]
