# Generated by Django 5.2.1 on 2025-05-22 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_userstepprogress_scheduler_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_hint', models.TextField(verbose_name='generated hint')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('assignment_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_hints', to='onboarding.userstepprogress', verbose_name='assignment step')),
            ],
            options={
                'verbose_name': 'AI hint',
                'verbose_name_plural': 'AI hints',
                'ordering': ['-created_at'],
            },
        ),
    ]
