# Generated by Django 5.2.1 on 2025-05-22 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0012_alter_lmsusertestresult_step_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lmsusertestresult',
            unique_together={('user', 'test')},
        ),
        migrations.AlterField(
            model_name='lmsusertestresult',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='onboarding.onboardingstep', verbose_name='step'),
        ),
    ]
