# Generated by Django 5.2.1 on 2025-05-23 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_alter_lmsusertestresult_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingstep',
            name='is_virtual_meeting',
            field=models.BooleanField(default=False, verbose_name='is virtual meeting'),
        ),
        migrations.CreateModel(
            name='VirtualMeetingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('meeting_link', models.URLField(blank=True, verbose_name='meeting link')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_meetings', to=settings.AUTH_USER_MODEL, verbose_name='assigned user')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_meeting_slots', to='onboarding.onboardingstep', verbose_name='step')),
            ],
            options={
                'verbose_name': 'virtual meeting slot',
                'verbose_name_plural': 'virtual meeting slots',
                'ordering': ['start_time'],
            },
        ),
    ]
