# Generated by Django 5.2.1 on 2025-05-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0014_onboardingstep_is_virtual_meeting_virtualmeetingslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatmessage',
            name='step_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_chat_messages', to='onboarding.userstepprogress', verbose_name='step progress'),
        ),
    ]
