# Generated by Django 5.2.1 on 2025-05-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreward',
            name='name',
        ),
        migrations.AddField(
            model_name='userreward',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='userreward',
            name='title',
            field=models.CharField(default='Legacy Achievement', max_length=255, verbose_name='title'),
        ),
    ]
