# Generated by Django 5.2.1 on 2025-05-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_remove_userreward_name_userreward_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreward',
            options={'verbose_name': 'user reward', 'verbose_name_plural': 'user rewards'},
        ),
        migrations.AlterField(
            model_name='userreward',
            name='achievement_id',
            field=models.CharField(max_length=50, verbose_name='achievement ID'),
        ),
        migrations.AlterField(
            model_name='userreward',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='userreward',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='userreward',
            name='reward_type',
            field=models.CharField(choices=[('achievement', 'Achievement'), ('level', 'Level'), ('special', 'Special')], max_length=20, verbose_name='reward type'),
        ),
        migrations.AlterField(
            model_name='userreward',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
