# Generated by Django 5.2.1 on 2025-05-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_alter_userreward_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='achievement_id',
            field=models.CharField(
                default='default_achievement', max_length=50, verbose_name='achievement ID'),
            preserve_default=False,
        ),
    ]
