"""Extended user fields

Revision ID: 20250426_1000
Revises: a6085ee672fa
Create Date: 2025-04-26 10:00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250426_1000'
down_revision: Union[str, None] = 'a6085ee672fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column(
        'middle_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column(
        'birth_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('users', sa.Column(
        'manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_manager', 'users',
                          'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_manager', 'users', type_='foreignkey')
    op.drop_column('users', 'manager_id')
    op.drop_column('users', 'photo')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
