# Generated by Django 5.2.1 on 2025-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_notifications_enabled_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='notification settings'),
        ),
    ]
