# Generated by Django 5.2.1 on 2025-06-02 07:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_add_manager_field'),
        ('onboarding', '0019_alter_attachment_id_alter_enhancedlmsquestion_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('slow_progress', 'Slow Progress'), ('skipped_feedback', 'Skipped Feedback'), ('test_failures', 'Test Failures'), ('mentor_reassignments', 'Mentor Reassignments'), ('unusual_activity', 'Unusual Activity Pattern')], max_length=30, verbose_name='anomaly type')),
                ('description', models.TextField(verbose_name='description')),
                ('details', models.JSONField(default=dict, verbose_name='details')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='detected at')),
                ('resolved', models.BooleanField(default=False, verbose_name='resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='resolution notes')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='onboarding.useronboardingassignment', verbose_name='assignment')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_anomalies', to='departments.department', verbose_name='department')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='onboarding.userstepprogress', verbose_name='step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_anomalies', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'onboarding anomaly',
                'verbose_name_plural': 'onboarding anomalies',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['user', 'anomaly_type'], name='onboarding__user_id_72afc9_idx'), models.Index(fields=['department', 'anomaly_type'], name='onboarding__departm_902dc6_idx'), models.Index(fields=['resolved', 'detected_at'], name='onboarding__resolve_7cfb97_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingDepartmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_onboardings', models.PositiveIntegerField(verbose_name='active onboardings')),
                ('completed_onboardings', models.PositiveIntegerField(verbose_name='completed onboardings')),
                ('avg_completion_time', models.DurationField(blank=True, null=True, verbose_name='average completion time')),
                ('avg_completion_percentage', models.FloatField(verbose_name='average completion percentage')),
                ('risk_factor', models.FloatField(help_text='Overall risk factor for the department', verbose_name='risk factor')),
                ('most_common_bottlenecks', models.JSONField(default=dict, verbose_name='most common bottlenecks')),
                ('summary_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='summary date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_summaries', to='departments.department', verbose_name='department')),
            ],
            options={
                'verbose_name': 'onboarding department summary',
                'verbose_name_plural': 'onboarding department summaries',
                'ordering': ['-summary_date'],
                'indexes': [models.Index(fields=['department', 'summary_date'], name='onboarding__departm_a87787_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percentage', models.FloatField(verbose_name='completion percentage')),
                ('steps_total', models.PositiveIntegerField(verbose_name='total steps')),
                ('steps_completed', models.PositiveIntegerField(verbose_name='completed steps')),
                ('steps_in_progress', models.PositiveIntegerField(verbose_name='steps in progress')),
                ('steps_not_started', models.PositiveIntegerField(verbose_name='steps not started')),
                ('steps_overdue', models.PositiveIntegerField(default=0, verbose_name='overdue steps')),
                ('avg_step_completion_time', models.DurationField(blank=True, null=True, verbose_name='average step completion time')),
                ('last_activity_time', models.DateTimeField(blank=True, null=True, verbose_name='last activity time')),
                ('snapshot_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='snapshot date')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to='onboarding.useronboardingassignment', verbose_name='assignment')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_snapshots', to='departments.department', verbose_name='department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'onboarding progress snapshot',
                'verbose_name_plural': 'onboarding progress snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['user', 'snapshot_date'], name='onboarding__user_id_a07fbc_idx'), models.Index(fields=['department', 'snapshot_date'], name='onboarding__departm_575ceb_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingRiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('completion', 'Completion Risk'), ('delay', 'Delay Risk'), ('engagement', 'Engagement Risk'), ('knowledge', 'Knowledge Retention Risk')], max_length=20, verbose_name='risk type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, verbose_name='severity')),
                ('probability', models.FloatField(help_text='Probability from 0.0 to 1.0', verbose_name='probability')),
                ('factors', models.JSONField(default=dict, help_text='Factors contributing to this risk', verbose_name='contributing factors')),
                ('estimated_impact', models.TextField(blank=True, verbose_name='estimated impact')),
                ('recommendation', models.TextField(blank=True, verbose_name='recommendation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_predictions', to='onboarding.useronboardingassignment', verbose_name='assignment')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_risks', to='departments.department', verbose_name='department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_predictions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'onboarding risk prediction',
                'verbose_name_plural': 'onboarding risk predictions',
                'ordering': ['-probability', '-created_at'],
                'indexes': [models.Index(fields=['user', 'risk_type'], name='onboarding__user_id_fbd3d1_idx'), models.Index(fields=['assignment', 'risk_type'], name='onboarding__assignm_8524e2_idx'), models.Index(fields=['department', 'risk_type'], name='onboarding__departm_bc014c_idx'), models.Index(fields=['created_at'], name='onboarding__created_2cc794_idx')],
            },
        ),
    ]
