# Generated by Django 5.2.1 on 2025-05-31 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0019_alter_attachment_id_alter_enhancedlmsquestion_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=20, verbose_name='type')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='is anonymous')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feedback_templates', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'feedback template',
                'verbose_name_plural': 'feedback templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('type', models.CharField(choices=[('scale', 'Scale'), ('text', 'Text'), ('multiple_choice', 'Multiple Choice')], default='text', max_length=20, verbose_name='type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='options')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='feedback.feedbacktemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'feedback question',
                'verbose_name_plural': 'feedback questions',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='is anonymous')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('onboarding_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_feedbacks', to='onboarding.onboardingstep', verbose_name='onboarding step')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='submitter')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to='feedback.feedbacktemplate', verbose_name='template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user feedback',
                'verbose_name_plural': 'user feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('problem_area', 'Problem Area'), ('summary', 'Summary'), ('risk', 'Risk'), ('satisfaction', 'Satisfaction Index')], default='summary', max_length=20, verbose_name='type')),
                ('content', models.TextField(verbose_name='content')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='confidence score')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='feedback.feedbacktemplate', verbose_name='template')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='feedback.userfeedback', verbose_name='feedback')),
            ],
            options={
                'verbose_name': 'feedback insight',
                'verbose_name_plural': 'feedback insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='text answer')),
                ('scale_answer', models.IntegerField(blank=True, null=True, verbose_name='scale answer')),
                ('choice_answer', models.JSONField(blank=True, null=True, verbose_name='choice answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.feedbackquestion', verbose_name='question')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.userfeedback', verbose_name='feedback')),
            ],
            options={
                'verbose_name': 'feedback answer',
                'verbose_name_plural': 'feedback answers',
                'unique_together': {('feedback', 'question')},
            },
        ),
    ]
